# Generated by Django 5.1 on 2024-09-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstore', '0004_product_hover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
