# Generated by Django 5.1 on 2024-09-23 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourstore', '0006_product_is_new_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new_launch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='launch_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
